sft:
  max_num_epochs: 1
  max_num_steps: 1000000
  val_period: -1  # Disable validation
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

checkpointing:
  enabled: true
  checkpoint_dir: results/sft_openmathinstruct2_qwen30ba3b
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 500  # Ignored when save_every_epoch is true
  save_every_epoch: true  # Save checkpoint at the end of every epoch

policy:
  model_name: "Qwen/Qwen3-30B-A3B"
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 512
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  precision: bfloat16
  
  dtensor_cfg:
    enabled: false
    
  dynamic_batching:
    enabled: false
    
  sequence_packing:
    enabled: false
    
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  max_grad_norm: 100000
  optimizer: null
  
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: true
    converter_type: "LlamaForCausalLM"
    tensor_model_parallel_size: 2
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 8
    pipeline_model_parallel_size: 1
    sequence_parallel: true
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    freeze_moe_router: false
    moe_router_dtype: null
    moe_router_load_balancing_type: "aux_loss"
    moe_router_bias_update_rate: 1e-3
    moe_token_dispatcher_type: "alltoall"
    moe_grouped_gemm: true
    apply_rope_fusion: True

    optimizer:
      optimizer: "adam"
      lr: 2e-5
      min_lr: 7.0e-7
      weight_decay: 0.01
      bf16: true
      fp16: false
      params_dtype: "float32"
      
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-8
      
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true
      
      clip_grad: ${policy.max_grad_norm}
      
    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_decay_iters: 1855
      lr_warmup_iters: 125
      lr_warmup_init: 0
      
    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      data_parallel_sharding_strategy: "optim_grads_params"

    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:False"

data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "openmathinstruct2"
  prompt_file: examples/prompts/math.txt
  split: "train_1M"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  output_key: 'generated_solution'

logger:
  log_dir: logs/sft-openmathinstruct2-qwen30ba3b  # Base directory for all logs
  wandb_enabled: false
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  num_val_samples_to_print: 0
  wandb:
    project: nemo-rl
    name: sft-openmathinstruct2-qwen30ba3b  # Base directory for all logs
  tensorboard:
    log_dir: tb_logs-sft-openmathinstruct2-qwen30ba3b  # Base directory for all logs
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 4